#!/bin/sh

addGroup () {
    GROUP_NAME="$1"

    if getent group "$GROUP_NAME" > /dev/null 2>&1; then
        echo "Group '$GROUP_NAME' already exists."
    else
        sudo groupadd "$GROUP_NAME"
        echo "Group '$GROUP_NAME' has been added."
    fi
}


# 检查用户 lingmolive 是否存在
if id "lingmolive" > /dev/null 2>&1; then
    echo "用户 lingmolive 已存在"
    addGroup autologin
    addGroup nopasswdlogin
    usermod -G autologin,nopasswdlogin lingmolive
else
    echo "用户 lingmolive 不存在，创建用户"
    addGroup autologin
    addGroup nopasswdlogin
    useradd -mG autologin,nopasswdlogin -s /bin/bash lingmolive
fi

# 更新 lingmolive 用户的密码
echo 'lingmolive:live' | chpasswd
echo "lingmolive ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/lingmolive

# 更新 root 用户的密码
echo 'root:root' | chpasswd