#!/bin/sh

# 检查用户 lingmolive 是否存在
if id "lingmolive" &>/dev/null; then
    echo "用户 lingmolive 已存在"
else
    echo "用户 lingmolive 不存在，创建用户"
    useradd lingmolive
fi

# 更新 lingmolive 用户的密码
echo 'lingmolive:live' | chpasswd
echo "lingmolive ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/lingmolive

# 更新 root 用户的密码
echo 'root:root' | chpasswd