name: Daily Build

permissions: write-all

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "59 15 * * *"
  workflow_dispatch:
jobs:
  debian:
    name: Building iso disk image
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'

      - uses: actions/checkout@v3

      - name: Set up Debian container
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/library/debian:trixie-slim
          options: --privileged -v ${{ github.workspace }}:/work
          run: |
            cd /work
            apt update; apt install git fakeroot live-build debootstrap debian-cd simple-cdd xorriso squashfs-tools debootstrap mtools -y
            cp -v  /usr/share/debootstrap/scripts/sid /usr/share/debootstrap/scripts/hydrogen
            git config --global --add safe.directory /work
            bash ./build.sh

      - name: Compress image
        run: |
          mkdir artifacts
          tar -czvf ./artifacts/lingmo_daily_$(date +%Y%m%d_%H%M%S).tar.gz images
            
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ${{ github.workspace }}/artifacts/*
          compression-level: 9 # maximum compression
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
